# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
#        Symfony\Component\Security\Core\User\User: 
#            algorithm: bcrypt
#            cost: 12
        AppBundle\Entity\User:
            algorithm: bcrypt   
            
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: 
#                 users:
#                    ryan:
#                        password: $2y$12$T/x1bbNgoFHHN5UihQpSlOz7P27C8zpNROP1T/XJLPqN/U2fcZeg
#                        roles: 'ROLE_USER'
#                    admin:
#                        password: $2y$12$tT/o.g2T.1QzyS89mynrrOUfV2a5zexU0OtYdWySfWV7ETMZIcIB2
#                        roles: 'ROLE_ADMIN'
        our_db_provider:
                    entity:
                        class: AppBundle:User
                        # if you're using multiple entity managers
                        # manager_name: customer
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        users:
            pattern: ^/
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path:   /logout
                target: /login
#        blog_admin:
#            pattern: ^/blog/admin
#            anonymous: false
#            http_basic:
#                realm: "Blog Admin Panel"
#        main:
#            anonymous: ~
            
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        

                
    access_control:
        # require ROLE_ADMIN for /admin*
#        - { path: ^/blog/admin, roles: ROLE_ADMIN }